### ISSUE TITLE
I can't compil it

### ISSUE THREAD

**Issue by PowaBanga** [jsravn/xmpp-uri#1]
~/xmpp-uri$ make install
Package pidgin was not found in the pkg-config search path.
Perhaps you should add the directory containing `pidgin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pidgin' found
Package pidgin was not found in the pkg-config search path.
Perhaps you should add the directory containing`pidgin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pidgin' found
gcc -O2 -Wall -g --std=gnu99  -fPIC -c xmpp_uri.c -o xmpp_uri.o
xmpp_uri.c:21:18: fatal error: glib.h: Aucun fichier ou dossier de ce type
 #include <glib.h>
                  ^
compilation terminated.
Makefile:46: recipe for target 'xmpp_uri.o' failed
make: **\* [xmpp_uri.o] Error 1
lio@lio-HP-G62-Notebook-PC:~/xmpp-uri$ make install
Package pidgin was not found in the pkg-config search path.
Perhaps you should add the directory containing `pidgin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pidgin' found
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing`gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
Package pidgin was not found in the pkg-config search path.
Perhaps you should add the directory containing `pidgin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pidgin' found
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing`gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
gcc -O2 -Wall -g --std=gnu99  -fPIC -c xmpp_uri.c -o xmpp_uri.o
xmpp_uri.c:21:18: fatal error: glib.h: Aucun fichier ou dossier de ce type
 #include <glib.h>
                  ^
compilation terminated.
Makefile:46: recipe for target 'xmpp_uri.o' failed
make: **\* [xmpp_uri.o] Error 1

What must I do ??
I'am on Ubuntu-gnome 14.10 AMD64 gnome-shell 3.14.1

**Comment by jsravn** [comment]
It looks like you're missing the pidgin devel libraries. I haven't built this on ubuntu so I'm not sure what package you need.

**Comment by jsravn** [comment]
Try installing `libpurple-dev` and let me know.

**Comment by jsravn** [comment]
No response, gonna close it.
